---
title: "HW 5"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.wideth = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


## Problem 1

load the dataset

```{r}
set.seed(10)

iris_with_missing = 
  iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

clean the missing values

```{r}
clean_missing = function(var) {
  if (is.numeric(var)) {
      var = replace_na(var, mean(var, na.rm = TRUE))
  } else if (is.character(var)) {
      var = replace_na(var, "virginicia")
  }
}

iris_without_missing = vector("list", length = 5)

iris_without_missing = map_df(iris_with_missing, clean_missing)
```


## Problem 2

create a dataframe containing all file names

```{r}
study = list.files("./data")
```

create a function to read the file

```{r}
read_data = function(filenames) {
  data_path = "./data/"
  read_csv(file = str_c(data_path, filenames))
}
```

create a dataframe for the experiment data

```{r}
study_df = map_df(study, read_data)

study_df %>% 
  mutate(
    id = study
  )
```





